id: I475FCE57
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T19:56:50+00:00'
last_modified: '2022-06-08T12:52:19.659713+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W21493
  title: འཇམ་དཔལ་མཚན་བརྗོད་སྐད་ཡིག་གསུམ་འདུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B31B:
      image_group_id: I1697
      title: ''
      total_pages: 92
      order: 1
      base_file: B31B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
