id: P010340
initial_creation_type: ocr
source_metadata:
  id: bdr:W21493
  title: འཇམ་དཔལ་མཚན་བརྗོད་སྐད་ཡིག་གསུམ་འདུས།
  author: ''
  volumes:
    459c61046c9c4b6ba724c690dcf42634:
      image_group_id: I1697
      title: ''
      volume_number: 1
      total_pages: 92
