id: P010340
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-19 20:44:52.369460
source_metadata:
  id: bdr:W21493
  title: འཇམ་དཔལ་མཚན་བརྗོད་སྐད་ཡིག་གསུམ་འདུས།
  author: ''
  volumes:
    459c61046c9c4b6ba724c690dcf42634:
      image_group_id: I1697
      title: ''
      volume_number: 1
      total_pages: 92
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
